[tool.semantic_release]
version_variable = ["cllm/__init__.py:__version__"]
branch = "main"
commit_parser = "angular"

[tool.semantic_release.publish]
upload_to_pypi = true

[tool.semantic_release.build]
build_command = "python setup.py sdist bdist_wheel"

[tool.semantic_release.commit]
subject = "build: release v{version}"
author = "github-actions <actions@github.com>"

[tool.semantic_release.tag]
format = "v{version}"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
